* Yet Another Experimental Repository

This repository is reserved for self-teaching are re-learning the programming skills.

A playground of some sorts, not completely clean code, experimental, fun.
There will be possible re-implementations of a script in different programming languages.
What is this *NOT*? A place for serious, secure, final, production ready projects [fn:1].

* So, what is in this Repo?

The top-level directories are self-explanatory:
- Drafts are for very small chunks of code I write and use quickly, within a day, and almost never re-use.
- Projects are for more than that, of the same nature.
- Tutorials are the files created when using a directed tutorial.
- Other directories are more dedicated.
  - Backend
    - Task Tracker CLI
    - To-do List API
    - Workout Tracker API
  - Mine80: This requires explanation, basically a place for experimental [[https://github.com/nesbox/TIC-80][TIC-80]] carts.

* Cheat-sheet

Any small important note that /I/ have to know gets here.

*ASCII escape character* ~\x1b~ is supported in most languages. Even though Python has =\033= and shells have =\e=, this is more supported, so easier remember.

* Other
** About The Languages

*** Python

For almost anything productive! The S-rate language I hate.
- GUI: [[https://www.riverbankcomputing.com/static/Docs/PyQt6/][PyQt6]] ([[https://doc.qt.io/qt-6/][Qt6]]), [[https://kivymd.readthedocs.io/][KivyMD]] ([[http://kivy.org/][Kivy]])
- Data Analysis: [[https://pandas.pydata.org/][pandas]]

*** Lua

For almost anything, the underrated S-rated language /I love/.
Daily usage scripts, learning various programming concepts,
scripting, creating micro games and tools (LOVE2D, TIC-80).

** External Links

- [[https://sqrtminusone.xyz/posts/2021-05-01-org-python/][Replacing Jupyter Notebook with Org Mode]]
- [[https://www.johndcook.com/blog/2022/08/02/org-babel-vs-jupyter/][Org-mode as a lightweight notebook]]
- [[https://irreal.org/blog/?p=10720][Org-mode Versus Jupyter Notebook]]
- [[https://en.wikipedia.org/wiki/Programming_paradigm][Programming paradigms Wikipedia]]
- [[https://realpython.com/python-functional-programming/][Functional Programming in Python: When and How to Use It]]
- [[https://github.com/krzjoa/awesome-python-data-science][Awesome Python Data Science]]

*** [[https://www.geeksforgeeks.org/data-structures/][Geeks For Geeks - Data Structures]]

*** [[https://www.w3schools.com/datascience/ds_python.asp][W3Schools - Data Science]]                                       :python:

- [[https://www.w3schools.com/python/pandas/default.asp][Pandas]] - This library is used for structured data operations, like import CSV files, create dataframes, and data preparation
- [[https://www.w3schools.com/python/numpy_intro.asp][Numpy]] - This is a mathematical library. Has a powerful N-dimensional array object, linear algebra, Fourier transform, etc.
- [[https://www.w3schools.com/python/matplotlib_intro.asp][Matplotlib]] - This library is used for visualization of data.
- [[https://www.w3schools.com/python/scipy_intro.asp][SciPy]] - This library has linear algebra modules

*** [[https://github.com/o2sh/onefetch/][Onefetch]]

/To track the size of my repository locally/.

I hate that it does not support either Fennel or Janet!
However, I'm not using them (extensively) yet so it's forgivable ATM!
Currently the repository is mostly Python and Lua.


* License

*Almost* every piece of code written in this repository will be licensed under GPL-3.0, *unless stated otherwise*.
Also, files, drafts, and projects under MIT, AGPL-3.0, and Creative Commons licenses will be included.

See GNU General Public [[LICENSE]] local file, or its respective [[https://www.gnu.org/licenses/gpl-3.0.html][web page]].

#+begin_src
This repository is just a directory of followed tutorials to track my learning.
Copyright (C) 2024 Behnam (wired_unwell@noreply.codeberg.org)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
#+end_src

* Footnotes

[fn:1] In the case any "projects" here turn serious, I will release them in dedicated repositories. 
