* Description

YAER is Yet Another Experimental Repository, is reserved for partial
tracking my progress in self-study of several the programming skills.
A playground of some sorts, not completely clean code, experimental,
fun.  What is this *NOT*? A place for serious, secure, final,
production ready projects [fn:1], and not a programming portfolio.

* Structure

The top-level directories are self-explanatory. Drafts are small
standalone scripts, with possible duplicates in functionality but
different implementations. Tutorials are the files created when using
a directed tutorial. More important projects in /Projects/ and
/Backend/ include:

- Task Tracker CLI, written in [[https://python.org][Python]], using [[https://click.palletsprojects.com/][click]]. Tasks are stored in plain JSON. Followed [[https://roadmap.sh/projects/task-tracker][task tracker at Roadmap.sh]] specifications.
- To-Do List API, written in [[https://python.org][Python]], using [[https://flask.palletsprojects.com/][Flask]], [[https://click.palletsprojects.com/][click]], [[https://flask-sqlalchemy.readthedocs.io/][flask-sqlalchemy]], and [[https://python-poetry.org/][Poetry]]. TODO are stored in a [[https://www.sqlite.org/][SQLite3]] database. Followed [[https://roadmap.sh/projects/todo-list-api][todo list api at Roadmap.sh]] specifications.
- Workout Tracker API (developed in the =workouttracker= branch), written in [[https://python.org][Python]], using [[https://flask.palletsprojects.com/][Flask]], [[https://click.palletsprojects.com/][click]], [[https://flask-sqlalchemy.readthedocs.io/][Psycopg]], [[https://flask-jwt-extended.readthedocs.io/][flask jwt extended]], and [[https://python-poetry.org/][Poetry]]. Workouts are stored in a PostgreSQL database. Followed [[https://roadmap.sh/projects/todo-list-api][todo list api at Roadmap.sh]] specifications.

* Contact

My responsive email, also used for identification, is ~behnam_{birthday}@protonmail.com~.

* License

*Almost* every piece of code written in this repository will be licensed under GPL-3.0, *unless stated otherwise*.
Also, files, drafts, and projects under MIT, AGPL-3.0, and Creative Commons licenses will be included.

See GNU General Public [[LICENSE]] local file, or its respective [[https://www.gnu.org/licenses/gpl-3.0.html][web page]].

#+begin_src
This repository is just a directory of followed tutorials to track my learning.
Copyright (C) 2024 Behnam (wired_unwell@noreply.codeberg.org)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
#+end_src

* Footnotes

[fn:1] In the case any "projects" here turn serious, I will release them in dedicated repositories. 
